//
//  Terms.swift
//  havr
//
//  Created by Ismajl Marevci on 4/28/17.
//  Copyright © 2017 Tenton LLC. All rights reserved.
//

import Foundation

class Terms : NSObject {
    
    static var termsText = "TERMS OF USE\r\n" +
    "Welcome to HAVR (hereinafter referred to as “App”, “We”, “Us”, “Our”), owned and operated by Yousuf Mohammad (HAVR). The app is offered to you conditioned on your acceptance without modification of the terms, conditions, and notices contained herein (the \"Terms\"). \r\n" +
    "BY CLICKING ON THE \"ACCEPT\" BUTTON AT THE END OF THE AGREEMENT ACCEPTANCE FORM, USERS AGREE TO BE BOUND BY THE TERMS AND CONDITIONS OF THIS AGREEMENT. PLEASE READ THIS ENTIRE AGREEMENT CAREFULLY BEFORE ACCEPTING ITS TERMS. DOWNLOADING AND USAGE OF THIS APP BY YOU SIGNIFIES YOUR ASSENT TO THE FOLLOWING BINDING AGREEMENT.\r\n" +
    "Our App provides an online career and a social networking platform, which on one hand, it connects, job seekers and employers in terms of professional transactions and on the other hand, it connect individuals in through socializing. Our app acts as a facilitator and all commercial / contractual terms are offered by and agreed to between Users alone. You understand and agree that we are not a party to any agreement entered into between Users. We have no control over the conduct of Users using our app and services, and disclaim all liability in this regard.\r\n" +
    "By using the app, you agree to comply with and be legally bound by the terms and conditions of these Terms of Service (\"Terms\"). These Terms govern your access to and use of the app and Services and all Collective Content, and constitute a binding legal agreement between you and us. \r\n" +
    "Please read carefully these Terms and our Privacy Policy, which may be found at ______________________________________ (link to privacy policy), and which is incorporated by reference into these Terms. If you do not agree to these Terms, you have no right to obtain information from or otherwise continue using the app. Failure to use the app in accordance with these Terms may subject you to civil and criminal penalties. This app reserves the right to recover the cost of services, collection charges and lawyers fees from persons using the app fraudulently. This app reserves the right to initiate legal proceedings against such persons for fraudulent use of the app and any other unlawful acts or acts or omissions in breach of these terms and conditions.\r\n" +
    "The use of this app constitutes your consent to, and agreement to, abide by the most current version of these terms and conditions (the \"Terms\"). We may at any time revise these terms and conditions by updating the Terms. You agree to be bound by subsequent revisions and agree to review the Terms periodically for changes to the terms and conditions. The most up to date version of the Terms will always be available for your review under the \"Terms of Use\" link that appears at the bottom of the App.\r\n" +
    "PLEASE READ THESE TERMS OF USE AND CAREFULLY AS THEY CONTAIN IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES AND OBLIGATIONS. THESE INCLUDE VARIOUS LIMITATIONS AND EXCLUSIONS, AND A CLAUSE THAT GOVERNS THE JURISDICTION AND VENUE OF DISPUTES.\r\n" +
    "IN USING THIS APP YOU ARE DEEMED TO HAVE READ AND AGREED TO THE FOLLOWING TERMS AND CONDITIONS SET FORTH HEREIN. ANY INCIDENTAL DOCUMENTS AND LINKS MENTIONED SHALL BE CONSIDERED TO BE ACCEPTED JOINTLY WITH THESE TERMS. YOU AGREE TO USE THE APP ONLY IN STRICT INTERPRETATION AND ACCEPTANCE OF THESE TERMS AND ANY ACTIONS OR COMMITMENTS MADE WITHOUT REGARD TO THESE TERMS SHALL BE AT YOUR OWN RISK. THESE TERMS AND CONDITIONS FORM PART OF THE AGREEMENT BETWEEN THE USERS AND US. BY ACCESSING THIS APP, AND/OR UNDERTAKING TO PERFORM A SERVICE BY US INDICATES YOUR UNDERSTANDING, AGREEMENT TO AND ACCEPTANCE, OF THE DISCLAIMER NOTICE AND THE FULL TERMS AND CONDITIONS CONTAINED HEREIN.\r\n" +
    "1. INTERPRETATION:\r\n" +
    "1.1 The official language of these terms shall be English. \r\n" +
    "1.2 The headings and sub-headings are merely for convenience purpose and shall not be used for interpretation. \r\n" +
    "1.3 In case there exists a machine-readable version of this agreement arises a conflict with the human readable version, the later shall prevail. \r\n" +
    "2. DEFINITIONS:\r\n" +
    "2.1 \"Agreement\" means the terms and conditions as detailed herein including all schedules, appendices, annexures, privacy policy, other policies mentioned on the app and will include the references to this agreement as amended, negated, supplemented, varied or replaced from time to time.\r\n" +
    "2.2 “HAVR” means the online career and social platform and the services provided by it and its affiliates owned and operated by Yousuf Mohammad. The application provides a venue/platform for the Users to interact with each other in order to socialize and also interact regarding career opportunities.\r\n" +
    "2.3 \"Employers/recruiters\" shall mean the person or any legal entity who offers/lists/posts a job vacancy on LinkedIn, the entire information of which is extracted by our app and then uploaded onto our app. \r\n" +
    "2.4 “Job seekers” shall mean individuals who are actively searching for jobs, changing jobs, registering for job alert emails, uploading their resumes, applying for jobs posted by employers on LinkedIn, which is extracted by our app and uploaded on to our app. \r\n" +
    "2.5 \"Users\" shall mean and include individuals who interact with each other in order to make social connections and also Employers and Job seekers who are all required to create an account on our app in order to use or access the services provided on this app.\r\n" +
    "2.6 “Listings/Postings” shall mean the job vacancies, resumes/CV’s, pictures, videos etc. uploaded on our app, the information of which is extracted by our app from LinkedIn, Facebook etc. \r\n" +
    "2.7 “Account” shall mean the accounts created by the Users on our app in order to use the Services provided by us and require information such as User type (employer, job seeker), email address, username and password. \r\n" +
    "2.8 “Content” shall mean text, graphics, images, music, audio, video, information or other materials.\r\n" +
    "2.9 “User content” shall mean all Content that a user posts, uploads, publishes, submits or transmits to be made available through our app.\r\n" +
    "2.10 “HAVR Content” shall mean all Content that our app makes available through the app or Services, including any Content licensed from a third party, but excluding user Content. \r\n" +
    "2.11 “SNS” shall mean Social Networking Site such as Facebook, LinkedIn etc.\r\n" +
    "2.12 “Third parties” shall mean any outside parties, which are not a part of our app.\r\n" +
    "3. ELIGIBILITY:\r\n" +
    "3.1 You may use the Service only if you are at least eighteen (18) years of age and can form a binding contract with us, and only in compliance with this Agreement and all applicable local, state, national, and international laws, rules and regulations. \r\n" +
    "3.2 Any use or access to the Service by anyone under 18 is strictly prohibited and in violation of this Agreement. Our app reserves the right to terminate your membership and refuse to provide you with access to the app if we discover that you are under the age of 18 years. The Service is not available to any Users previously removed from the Service by us, unless we provide such Users with specific written authorization to re-use the Service. \r\n" +
    "3.3 If you use our app on behalf of a company, organization, or other entity, then (a) \"you\" includes you and that entity, and (b) you represent and warrant that you are an authorized representative of the entity with the authority to bind the entity to this Agreement, and that you agree to this Agreement on the entity's behalf. \r\n" +
    "3.4 You must not be a competitor of our app or use our Service for reasons that are in competition with us or otherwise to replicate some or all of the Service for any reason. \r\n" +
    "3.5 Except where additional terms and conditions are provided which are services/product specific, these terms and conditions supersede all previous representations, understandings, or agreements and shall prevail notwithstanding any variance with any other terms of any order submitted. By using the services of our app you agree to be bound by the Terms and Conditions.\r\n" +
    "4. REGISTRATION:\r\n" +
    "4.1 It is mandatory for the Users to create an account on our app in order to use our services. \r\n" +
    "4.2 In order to create an account and register with us you shall either create an account with us or you may register with us by using your valid account on the social networking service (“SNS”) such as Facebook or LinkedIn accounts (each such account, a “Third-Party Account”). If you access the Services through a SNS, you may link your Account with Third-Party Accounts, by allowing us to access your Third-Party Account, as is permitted under the applicable terms and conditions that govern your use of each Third-Party Account. You represent that you are entitled to disclose your Third-Party Account login information to us and/or grant us access to your Third-Party Account (including, but not limited to, for use for the purposes described herein) without breach by you of any of the terms and conditions that govern your use of the applicable Third-Party Account and without obligating us to pay any fees or making us subject to any usage limitations imposed by such third-party service providers. You have the ability to disable the connection between your Account and your Third-Party Accounts at any time by accessing the “Settings” section of the app. Please note that your relationship with the third-party service providers associated with your third-party accounts is governed solely by your agreement(s) with such third-party service providers, and we disclaim any liability for personally identifiable information that may be provided to it by such third-party service providers in violation of the privacy settings that you have set in such third-party accounts.\r\n" +
    "4.3 If a User wants to connect with a person socially, then he/she shall register on our app using their Facebook account and if the User wants connect with a person professionally then he/she shall register on our app using their LinkedIn account. If a User logs in by using his/her Facebook or LinkedIn account then we shall have the authority to access all your information mentioned on the said accounts, which shall then be uploaded onto our app after which the Users shall interact socially or professionally with one another via our app. If an enterprise (business) logs in using credentials from its Personal Page then our app shall take the personal information about their business and also take all the information regarding events and/or job postings that are mentioned on their personal page (Facebook, LinkedIn). Users will be able to find nearby events on the map that is within our app and then attend those events in order to interact with other people without a need to be matched traditionally (the connection breaks once the event is over) by interacting through messaging via our app. \r\n" +
    "A. Accounts:\r\n" +
    "a) In order to create an account directly with us, you must provide us with certain personal information including personal information such as user type, username, email address and password.\r\n" +
    "b) You represent and warrant that all required registration information you submit is truthful and accurate, and you will maintain the accuracy of such information. You are responsible for maintaining the confidentiality of your Account login information and are fully responsible for all activities that occur under your Account. You agree to immediately notify us of any unauthorized use, or suspected unauthorized use of your Account or any other breach of security. We cannot and will not be liable for any loss or damage arising from your failure to comply with the above requirements. You must not share your password or other access credentials with any other person or entity that is not authorized to access your account. Without limiting the foregoing, you are solely responsible for any activities or actions that occur under your website account access credentials. We encourage you to use a “strong” password (a password that includes a combination of upper and lower case letters, numbers, and symbols) with your account. We cannot and will not be liable for any loss or damage arising from your failure to comply with any of the above.\r\n" +
    "4.3 You agree to provide and maintain accurate, current and complete information about your Account. Without limiting the foregoing, in the event you change any of your personal information as mentioned above in this Agreement, you will update your Account information promptly.\r\n" +
    "4.4 When creating an Account, don’t:\r\n" +
    "a) Provide any false personal information to us (including without limitation a false username) or create any Account for anyone other than yourself without such other person’s permission;\r\n" +
    "b) Use a username that is the name of another person with the intent to impersonate that person;\r\n" +
    "c) Use a username that is subject to rights of another person without appropriate authorization; or\r\n" +
    "d) Use a username that is offensive, vulgar or obscene or otherwise in bad taste.\r\n" +
    "4.5 We reserve the right to suspend or terminate your Account if any information provided during the registration process or thereafter proves to be inaccurate, false or misleading or to reclaim any username that you create through the Service that violates our Terms. If you have reason to believe that your Account is no longer secure, then you must immediately notify us at info@havr.ca\r\n" +
    "4.6 You may not transfer or sell your HAVR account and User ID to another party. If you are registering as a business entity, you personally guarantee that you have the authority to bind the entity to this Agreement.\r\n" +
    "4.7 Our Services are not available to temporarily or indefinitely suspended Users. Our app reserves the right, in its sole discretion, to cancel unconfirmed or inactive accounts. Our app reserves the right to refuse service to anyone, for any reason, at any time.\r\n" +
    "4.8 One individual/entity can own only one account in his/her/its name.\r\n" +
    "4.9 You agree to comply with all local laws regarding online conduct and acceptable content. You are responsible for all applicable taxes. In addition, you must abide by our app’s policies as stated in the Agreement and all other policies listed on the app and all other operating rules, policies and procedures that may be published from time to time on the app by Company.\r\n" +
    "5. SERVICES:\r\n" +
    "5.1 Our app provides tools to Users to accomplish their goals.\r\n" +
    "5.2 Our app has the authority to extract information from Users’ Facebook or LinkedIn account depending on the account via which they register on our app. The information extracted by our app about the User is then uploaded on our app via which the Users can interact amongst themselves socially or professionally. \r\n" +
    "5.3 Our intelligent matchmaking and recommendation engine gets employers the most suitable candidates and job seekers the right employers. It also matches the individuals who wish to interact socially on our app by using the information mentioned on their Facebook account. \r\n" +
    "6. HAVR AS A PLATFORM:\r\n" +
    "6.1 Our app does not make any representation or warranty as to the attributes (such as legal title, creditworthiness, identity, etc.) of any of its Users. Users are advised to independently verify the bona fides of any particular User that they choose to deal/interact socially and/or professionally with on the app and use their best judgment in that behalf. \r\n" +
    "6.2 The app is only a venue through which Users can reach a larger base in order to interact professionally and socially. We are only providing a platform for communication between Users.\r\n" +
    "6.3 We neither guarantee any employment to job seekers nor assure employers of finding their required candidates. We shall not guarantee, refer, endorse, recommend, verify, and evaluate any Users on our app. \r\n" +
    "6.4 We do not guarantee the validity, accuracy, completeness, safety, legality, quality or applicability of the content on the app and anything spoken or written by Users. \r\n" +
    "6.5 You release and indemnify us and/or any of our shareholders, directors, officers, employees and representatives from any cost, damage, liability or other consequence of any of the actions of the Users of the app and specifically waive any claims that you may have in this behalf under any applicable law. Notwithstanding its reasonable efforts in that behalf, our app cannot control the information provided by other Users, which is made available on the app. You may find other User's information to be offensive, harmful, inaccurate, or deceptive. Please use caution and practice safe trading when using the app. Please note that there may be risks in dealing with foreign nationals, underage persons or people acting under false pretense. \r\n" +
    "6.6 You acknowledge and undertake that you are accessing the services on the app and transacting at your own risk and are using your best and prudent judgment before availing any services through the app. \r\n" +
    "7. NO RESPONSIBILITY:\r\n" +
    "7.1 We shall not be involved in any transactions/interaction between Users. \r\n" +
    "7.2 We do not control or verify the quality, relevance or accuracy of the information provided by Users or extracted from their Facebook and/or LinkedIn accounts.\r\n" +
    "7.3 Our App takes reasonable precautions to collect accurate information about the identity of the Users on our App. However, our App must inform Users that it is highly difficult for us to verify each and every User. Thus, we expressly state that our App does not provide any warranty as to the real identity or all other personally identifiable information about the Users.\r\n" +
    "8. OBLIGATIONS OF USERS:\r\n" +
    "8.1 Users shall not make arrangements outside of this platform in order to have any paid relations or any contact with each other contacted through our app. Users agree that any information or content that he or she or it posts, transmits or receives through our app shall not be considered confidential. \r\n" +
    "8.2 Users grant us an unlimited, irrevocable, royalty free license to use, reproduce, display, edit, copy, transmit, publicly perform, create derivative works, or communicate to the public any such information and content on a worldwide basis. \r\n" +
    "8.3 Users shall not take any actions that may undermine, disrupt or manipulate the integrity of the User feedback system on the app.\r\n" +
    "9. PAYMENTS:\r\n" +
    "9.1 Registration on our app is free for Users. Users will have access to all our services once they register on our app for free.\r\n" +
    "9.2 Our app reserves the right to add premium features in the future. However the main features will not be paid so users experience will not be affected in anyway.\r\n" +
    "9.3 The payments for the paid premium features shall be accepted via User’s valid credit card (visa, master card) only. \r\n" +
    "9.4 The services once purchased on our app shall not be subject to cancellation or refund. We might cancel the services or refund the amount only in certain exceptional cases (genuine and valid reason) at our sole discretion else all our purchases shall be final and binding.\r\n" +
    "9.5 Our app uses third party payment providers to receive payments from Users. We are not responsible for delays or erroneous transaction execution or cancellation of services/orders due to payment issues. \r\n" +
    "9.6 We take utmost care to work with 3rd party payment providers, but do not control their systems, processes, technology and work flows, hence cannot be held responsible for any fault at the end of payment providers. \r\n" +
    "9.7 Users understand and expressly authorize us to collect payment from or charge their credit card for availing our services.\r\n" +
    "9.8 Our app reserves the right to change or replace the payment gateway at its sole discretion without any reservation whatsoever. Our app stores bank information of the Users in order to make it easier for them to just click and pay without entering the details every time they avail our services. All transactions are completed through secure third party payment gateways and at no point of time we assume any liability for any loss of data or wrongful payment or invalid payment processing by such a third party. Users acknowledge that we will not be liable for any damages, interests or claims etc. resulting from not processing a Transaction/Transaction Price or any delay in processing a Transaction/Transaction Price which is beyond our control.\r\n" +
    "10. FRAUDULENT/DECLINED TRANSACTIONS:\r\n" +
    "10.1 Our app reserves the right to recover the cost of services, collection charges and lawyers' fees from persons using the app fraudulently. We reserve the right to initiate legal proceedings against such persons for fraudulent use of the app and any other unlawful act or acts or omissions in breach of these terms and conditions.\r\n" +
    "10.2 We shall be under no liability whatsoever in respect of any loss or damage arising directly or indirectly out of the decline of authorization for any Transaction, on Account of the Cardholder having exceeded the preset limit mutually agreed by us with our acquiring bank from time to time.\r\n" +
    "11. USE OF THE APP:\r\n" +
    "11.1 You understand and agree that the App merely provides communication services to its Users. Our app neither originates nor initiates the transmission nor selects the sender and receiver of the transmission nor selects nor modifies the information contained in the transmission. We have no control over contents of messages, feedbacks etc. by Users and do not provide any guarantee with respect to any such content and our app shall not be held liable for any loss suffered based on your reliance on or use of such data/content. \r\n" +
    "11.2 You shall not post, host, display, upload, modify, message, publish, transmit, update or share any information which:\r\n" +
    "(a) belongs to another person and to which You do not have any right;\r\n" +
    "(b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to \"indecent representation of women”;\r\n" +
    "(c) is misleading in any way;\r\n" +
    "(d) is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;\r\n" +
    "(e) harasses or advocates harassment of another person;\r\n" +
    "(f) involves the transmission of \"junk mail\", \"chain letters\", or unsolicited mass mailing or \"spamming\";\r\n" +
    "(g) promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libellous;\r\n" +
    "(h) infringes upon or violates any third party's rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity];\r\n" +
    "(i) promotes an illegal or unauthorized copy of another person's copyrighted work (see \"Copyright complaint\" below for instructions on how to lodge a complaint about uploaded copyrighted material), such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;\r\n" +
    "(j) contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);\r\n" +
    "(k) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;\r\n" +
    "(l) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;\r\n" +
    "(m) contains video, photographs, or images of another person (with a minor or an adult).\r\n" +
    "(n) tries to gain unauthorized access or exceeds the scope of authorized access to the app or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the app or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;\r\n" +
    "(o) engages in commercial activities and/or sales without our prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of \"virtual\" products;\r\n" +
    "(p) solicits gambling or engages in any gambling activity which we, in our sole discretion, believe is or could be construed as being illegal;\r\n" +
    "(q) interferes with another User's use and enjoyment of the app and enjoyment of similar services;\r\n" +
    "(r) refers to any app or URL that, in Our sole discretion, contains material that is inappropriate for the app or any other app, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.\r\n" +
    "(s) harm minors in any way;\r\n" +
    "(t) infringes any patent, trademark, copyright or other proprietary rights or third party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products;\r\n" +
    "(u) violates any law for the time being in force;\r\n" +
    "(v) deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;\r\n" +
    "(w) impersonate another person;\r\n" +
    "(x) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;\r\n" +
    "(y) threatens the unity, integrity, defense, security, sovereignty of Canada, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.\r\n" +
    "(z) shall not be false, inaccurate or misleading;\r\n" +
    "11.3 You shall not, directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.\r\n" +
    "11.4 You shall not create liability for us or cause us to lose (in whole or in part) the services of our Internet service provider (\"ISPs\") or other suppliers;\r\n" +
    "11.5 You shall not use any \"deep-link\", \"page-scrape\", \"robot\", \"spider\" or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the app or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the app or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the app. We reserve our right to bar any such activity.\r\n" +
    "11.6 You shall not attempt to gain unauthorized access to any portion or feature of the app, or any other systems or networks connected to the app or to any server, computer, network, or to any of the services offered on or through the app, by hacking, password \"mining\" or any other illegitimate means.\r\n" +
    "11.7 You shall not probe, scan or test the vulnerability of the app or any network connected to the app nor breach the security or authentication measures on the app or any network connected to the app. You may not reverse look-up, trace or seek to trace any information of any other User or visitor to app, or any other customer, including any account on the app not owned by You, to its source, or exploit the app or any service or information made available or offered by or through the app, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than Your own information, as provided for by the app.\r\n" +
    "11.8 You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about Us or the brand name or domain name used by Us, or otherwise engage in any conduct or action that might tarnish the image or reputation, of our app or otherwise tarnish or dilute any of our trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by us. You agree that you will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the app or our systems or networks, or any systems or networks connected to us.\r\n" +
    "11.9 You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the app or any transaction being conducted on the app, or with any other person's use of the app.\r\n" +
    "11.10 You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal you send to us on or through the app or any service offered on or through the app. You may not pretend that you are, or that you represent, someone else, or impersonate any other individual or entity.\r\n" +
    "11.11 You may not use the app or any content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of our app and / or others.\r\n" +
    "11.12 You shall solely enable us to use the information you supply us with, so that we are not violating any rights you might have in your Information, you agree to grant Us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights you have in your Information, in any media now known or not currently known, with respect to your Information. We will only use your information in accordance with the Terms of Use and Privacy Policy applicable to use of the app.\r\n" +
    "11.13 We reserve the right, but have no obligation, to monitor the materials posted on the app. Our app shall have the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Use. Notwithstanding this right, you remain solely responsible for the content of the materials you post on the app and in your private messages. Please be advised that such Content posted does not necessarily reflect our views. In no event shall our app assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on the app. You hereby represent and warrant that you have all necessary rights in and to all Content which you provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libellous, tortious, or otherwise unlawful information.\r\n" +
    "11.14 It is possible that any of the user (including unauthorized users or \"hackers\") may post or transmit offensive or obscene materials on the app and that other users may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about you due to your use of the app, and that the recipient may use such information to harass or injure you. We do not approve of such unauthorized uses, but by using the app, you acknowledge and agree that we are not responsible for the use of any personal information that you publicly disclose or share with others on the app. Please carefully select the type of information that you publicly disclose or share with others on the app.\r\n" +
    "11.15 We shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your own or through group/s of people, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services).\r\n" +
        "12. OWNERSHIP:\r\n" +
        "All right, title, and interest in and to the app (excluding postings/content provided by the users) is and will remain the exclusive property of HAVR and our licensors. The app service is protected by copyright, trademark, and other laws of Canada. Nothing in these Terms gives you a right to use the name of the app or app’s trademark or logo, or any other trademarks, logos, domain names, or other distinctive brand features relating to the app or located on the app. Any feedback, comments, and suggestions you may provide regarding the app (“Feedback”) are entirely voluntary and you grant us a perpetual, irrevocable, worldwide, royalty-free license (with the right to sublicense) to use, reproduce, modify, create derivative works of, commercialize, and otherwise freely exploit such Feedback (including, but not limited to, all Rights therein) as we see fit and without any payment or other obligation to you.\r\n" +
        "13. INTELLECTUAL PROPERTY RIGHTS:\r\n" +
        "13.1 Our app, our suppliers and licensors expressly reserve all intellectual property rights in all text, programs, products, processes, technology, content and other materials, which appear on this app. Access to this app does not confer and shall not be considered as conferring upon anyone any license under any of HAVR or any third party's intellectual property rights. All rights, including copyright, in this app are owned by or licensed to us or third party suppliers. Any use of this app or its contents, including copying or storing it or them in whole or part, other than for your own personal, non-commercial use is prohibited without the permission of our app. You cannot modify, distribute or re-post anything on this app for any purpose.\r\n" +
        "13.2 The app names and logos and all related service and our slogans are the trademarks or service marks of HAVR. All other marks are the property of their respective companies. No trademark or service mark license is granted in connection with the materials contained on this app. Access to this app does not authorize anyone to use any name, logo or mark in any manner.\r\n" +
        "13.3 All materials, including images, text, illustrations, designs, icons, photographs, programs, music clips or downloads, video clips and written and other materials that are part of this app (collectively, the \"Contents\") are intended solely for personal, non-commercial use. You may download or copy the Contents and other downloadable materials displayed on the app for your personal use only. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying. You may not reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from, sell or participate in any sale of or exploit in any way, in whole or in part, any of the Contents, the company or any related software. All software used on this app is the property of our app or its suppliers and protected by copyright laws of Canada. The Contents and software on this app may be used only as a referral resource. Any other use, including the reproduction, modification, distribution, transmission, republication, display, or performance, of the Contents on this app is strictly prohibited. Unless otherwise noted, all Contents are copyrights, trademarks and/or other intellectual property owned, controlled or licensed by our app, one of its affiliates or by third parties who have licensed their materials to us and are protected by copyright laws of Canada. The compilation (meaning the collection, arrangement, and assembly) of all Contents on this app is the exclusive property of our company and is also protected by Copyright laws of Canada.\r\n" +
        "13.4 We have the right to remove the Content alleged to be infringing without prior notice, at our sole discretion, and without liability to you. In appropriate circumstances, we will also terminate a user’s account if we determine that the user is a repeat infringer.\r\n" +
        "13.5 While we are not obligated to review User Submitted Materials for copyright infringement, we are committed to protecting copyrights and expect users of our app to do the same. If you believe in good faith that any material used or displayed on or through our app infringes your copyright, you (or your agent) may send us a notice requesting that the material be removed, or access to it blocked, please provide us with the following information: \r\n" +
        "(i) a physical or electronic signature of the copyright owner or a person authorized to act on their behalf; \r\n" +
        "(ii) identification of the copyrighted work claimed to have been infringed;\r\n" +
        "(iii) identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material;\r\n" +
        "(iv) Your contact information, including your address, telephone number and an email address; \r\n" +
        "(v) a statement by you that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and\r\n" +
        "(vi) a statement that the information in the notification is accurate, and that You are authorized to act on behalf of the copyright owner.\r\n" +
        "13.6 We have the right to remove the Content alleged to be infringing without prior notice, at our sole discretion, and without liability to you. In appropriate circumstances, we will also terminate a member’s account if we determine that the member is a repeat infringer.\r\n" +
        "13.7 You should assume that everything that you see or read on this app is copyrighted unless otherwise noted and may not be copied, reproduced, distributed, modified, published, downloaded, posted, or transmitted in any way, without the prior written consent of our app or other copyright owner, EXCEPT: You may print copies of the material for your personal, noncommercial use only, provided that you do not delete or change any copyright, trademark, or other proprietary notices. Unless otherwise indicated, all marks displayed on our Internet sites are subject to the trademark rights of our app, including our name and Logo, corporate logos and emblems. Modifying, distributing or using for any purpose the material in any of our app which is copyrighted or otherwise protected under intellectual property laws directly violates our intellectual property rights. The material contained in this app is copyrighted, is protected by worldwide copyright laws and treaty provisions, and is provided for lawful purposes only.\r\n" +
        "14. REVIEWS, FEEDBACK, SUBMISSIONS:\r\n" +
        "14.1 All reviews, comments, feedback, postcards, suggestions, ideas, and other submissions disclosed, submitted or offered to us on this app or otherwise disclosed, submitted or offered in connection with your use of this app (collectively, the \"Comments\") shall be and remain our property. Such disclosure, submission or offer of any Comments shall constitute an assignment to us of all worldwide rights, titles and interests in all copyrights and other intellectual properties in the Comments. Thus, we exclusively own all such rights, titles and interests and shall not be limited in any way in its use, commercial or otherwise, of any Comments. We will be entitled to use, reproduce, disclose, modify, adapt, create derivative works from, publish, display and distribute any Comments you submit for any purpose whatsoever, without restriction and without compensating you in any way. \r\n" +
        "14.2 We are and shall be under no obligation (1) to maintain any Comments in confidence; (2) to pay you any compensation for any Comments; or (3) to respond to any Comments. You agree that any Comments submitted by you to the app will not violate this policy or any right of any third party, including copyright, trademark, privacy or other personal or proprietary right(s), and will not cause injury to any person or entity. You further agree that no Comments submitted by you to the app will be or contain libelous or otherwise unlawful, threatening, abusive or obscene material, or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any form of \"spam\".\r\n" +
        "14.3 Our app does not regularly review posted Comments, but does reserve the right (but not the obligation) to monitor and edit or remove any Comments submitted to the app. You grant us the right to use the name that you submit in connection with any Comments. You agree not to use a false email address, impersonate any person or entity, or otherwise mislead as to the origin of any Comments you submit. You are and shall remain solely responsible for the content of any Comments you make and you agree to indemnify us and our affiliates for all claims resulting from any Comments you submit. We and our affiliates take no responsibility and assume no liability for any Comments submitted by you or any third party.\r\n" +
        "15. INDEMNITY:\r\n" +
        "Users agree to defend, indemnify and hold harmless our app, its employees, directors, officers, agents and their successors and assigns from and against any and all claims, liabilities, damages, losses, costs and expenses, including attorney's fees, caused by or arising out of claims based upon your actions or inactions, which may result in any loss or liability to our app or any third party including but not limited to breach of any warranties, representations or undertakings or in relation to the non-fulfillment of any of your obligations under this User Agreement or arising out of your violation of any applicable laws, regulations including but not limited to Intellectual Property Rights, payment of statutory dues and taxes, claim of libel, defamation, violation of rights of privacy or publicity, loss of service by other subscribers and infringement of intellectual property or other rights. This clause shall survive the expiry or termination of this User Agreement.\r\n" +
        "16. APP STORES:\r\n" +
        "You acknowledge and agree that the availability of the App is dependent on the App Store from which you received the App license. You acknowledge that the Terms are between you and us and not with the App Store. We, not the App Store, is solely responsible for the app Properties, including the App, the content thereof, maintenance, support services, and warranty therefore, and addressing any claims relating thereto (e.g., product liability, legal compliance or intellectual property infringement). In order to use the App, you must have access to a wireless network or other Internet enable network, and you agree to pay all fees associated with such access. You also agree to pay all fees (if any) charged by the App Store in connection with the Company Properties, including the App. You agree to comply with, and your license to use the App is conditioned upon your compliance with, all applicable third-party terms of agreement (e.g., the App Store’s terms and policies) when using the Company Properties, including the App. You acknowledge that the App Store (and its subsidiaries) are third-party beneficiaries of the Terms and will have the right to enforce them.\r\n" +
        "17. TERMINATION:\r\n" +
        "17.1 We may, at any time and without notice, suspend, cancel, or terminate your right to use the app (or any portion of the app). In the event of suspension, cancellation, or termination, you are no longer authorized to access the part of the app affected by such suspension, cancellation, or termination. In the event of any suspension, cancellation, or termination, the restrictions imposed on you with respect to material downloaded from the app, and the disclaimers and limitations of liabilities set forth in the Agreement, shall survive.\r\n" +
        "17.2 Depending upon the nature of termination, subject to the provisions laid down in this agreement, we may or may not refund you for any payment due or kept with us. We will review the refund requests case by case. Without limiting the foregoing, we may close, suspend or limit your access to your Account:\r\n" +
        "• if we determine that you have breached, or are acting in breach of, this User Agreement;\r\n" +
        "• if you attempt to negotiate the actual price privately, avoiding fees;\r\n" +
        "• if we determine that you have breached legal liabilities (actual or potential), including infringing someone else's Intellectual Property Rights;\r\n" +
        "• if we determine that you have engaged, or are engaging, in fraudulent, or illegal activities;\r\n" +
        "• you do not respond to account verification requests;\r\n" +
        "• you do not complete account verification when requested within 3 months of the date of request;\r\n" +
        "• to manage any risk of loss to us, a User, or any other person; or\r\n" +
        "• For other similar reasons.\r\n" +
        "17.3 Without limiting our other remedies, to the extent you have breached this User Agreement, you must pay us all fees owed to us and reimburse us for all losses and costs (including any and all of our employee time) and reasonable expenses (including legal fees) related to investigating such breach and collecting such fees.\r\n" +
        "17.4 In the event that we close your Account, you will have no claim whatsoever against us in respect of any such suspension or termination of your Account.\r\n" +
        "18. CLOSING YOUR ACCOUNT:\r\n" +
        "We allow you to close your account with us if you send us a request for the same at info@havr.ca. However, you must not have any outstanding payment, dispute, listing or any other matter unresolved with us or third parties through our app. \r\n" +
        "19. INACTIVE ACCOUNTS:\r\n" +
        "We reserve the right to terminate or suspend an account, which has been inactive for more than one year without any activity or subscription payment left. We will notify you at the email provided with us three times at 2 months, 1 month and 24 hours prior to the suspension. \r\n" +
        "20. GOVERNING LAW AND ATTORNEY’S FEES:\r\n" +
        "20.1 This Agreement shall be governed by and construed in accordance with the laws of Canada, without regard to its choice of law principles.  \r\n" +
        "20.2 The parties consent to exclusive jurisdiction and venue in the province courts sitting in Ontario, Canada. \r\n" +
        "20.3 In any action or suit to enforce any right or remedy under this agreement or to interpret any provision of this agreement, the prevailing party shall be entitled to recover its reasonable attorney’s fees, costs and other expenses.  \r\n" +
        "21. RESOLUTION OF DISPUTES AND JURISDICTION:\r\n" +
        "21.1 Disputes with our app:\r\n" +
        "a) Any dispute arising from or relating to the subject matter of this Agreement shall be finally settled by arbitration in Ontario, Canada using the English language in accordance with the Arbitration Rules and Procedures then in effect, by one commercial arbitrator with substantial experience in resolving intellectual property and commercial contract disputes, who shall be selected from the appropriate list of arbitrators in accordance with the Arbitration Rules and Procedures of Canada. \r\n" +
        "b) The prevailing party in any arbitration or other proceeding arising under this Agreement shall be entitled to receive reimbursement of its reasonable expenses (including reasonable attorneys' fees, expert witness fees and all other expenses) incurred in connection therewith. \r\n" +
        "c) Judgment upon the award so rendered may be entered in a court having jurisdiction or application may be made to such court for judicial acceptance of any award and an order of enforcement, as the case may be. \r\n" +
        "d) Notwithstanding the foregoing, each party shall have the right to institute an action in a court of proper jurisdiction for injunctive or other equitable relief pending a final decision by the arbitrator. \r\n" +
        "e) For all purposes of this Agreement, the parties consent to exclusive jurisdiction and venue in Ontario, Canada.\r\n" +
        "f) Use of the app is not authorized in any jurisdiction that does not give effect to all provisions of the Agreement, including without limitation, this section. You and we agree that any cause of action arising out of or related to the app (including, but not limited to, any services provided or made available therein) or this Agreement must commence within one (1) year after the cause of action arose; otherwise, such cause of action is permanently barred.\r\n" +
        "21.2 Disputes amongst Users or Third Parties:\r\n" +
        "a) In the event a dispute arises between you and another user or a third party, we encourage you to first contact the user or third party to resolve the dispute amicably. \r\n" +
        "b) If Users are unable to resolve a dispute resulting from a transaction that occurs on our app, they may choose to participate in our app’s case system in order to resolve the dispute. Cases are escalated for review and resolution by customer service. Our app provides its dispute resolution process for the benefit of users. Our app does so in its sole discretion, and our app has no obligation to resolve disputes between users or between users and outside parties. To the extent that we attempt to resolve a dispute, we will do so in good faith based solely on our policies. We will not make judgments regarding legal issues or claims.\r\n" +
        "c) You may also report user-to-user disputes to your local law enforcement or a certified mediation or arbitration entity, as applicable. \r\n" +
        "d) You release us (and our officers, directors, agents, subsidiaries, joint ventures and employees) from any and all claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with disputes with one or more users, or an outside party. \r\n" +
        "22. ACCESS AND INTERFERENCE:\r\n" +
        "22.1 Our app may contain robot exclusion headers, which contain internal rules for software usage. Much of the information on our app is updated on a real-time basis and is proprietary or is licensed to us by our users or third parties. You agree that you will not use any robot, spider, scraper or other automated means to access our app for any purpose whatsoever, except to the extent expressly permitted by us in writing. Additionally, you agree that you will not:\r\n" +
        "a) Take any action that imposes, or may impose, in our app’s sole discretion, an unreasonable or disproportionately large load on our app’s infrastructure;\r\n" +
        "b) Copy, reproduce, modify, create derivative works from, distribute or publicly display any user Content (except for your Content) or other allowed uses as set out in our Guidelines from the app except to the extent expressly permitted by and in compliance with Terms of Use or otherwise without the prior express written permission of our app and the appropriate third party, as applicable;\r\n" +
        "c) Interfere or attempt to interfere with the proper working of the app or any activities conducted on the app;\r\n" +
        "d) Bypass our app’s robot exclusion headers or other measures we may use to prevent or restrict access to our app.\r\n" +
        "23. PRIVACY:\r\n" +
        "We respect the privacy of our users and take all possible measures to protect them. Our Privacy Policy has all the practices, measures and steps we have to protect your privacy. \r\n" +
        "24. SECURITY:\r\n" +
    "We have employed highest possible security measures to protect your data, which is stored with us. While we take all possible measure steps, you must immediately notify us upon becoming aware of any unauthorized access, any illegal online activity or any other security breach pertaining to the app, your Account or our Services and do everything under your control to mitigate the unauthorized access or security breach (including providing us the evidence and notifying appropriate authorities). You are solely responsible for securing your password. We will not be liable for any loss or damage arising from unauthorized access of your account resulting from your failure to secure your password.\r\n" +
        "25. NO INSURANCE:\r\n" +
        "You expressly agree that our app does not offer any insurance or guarantee as to the claims, offers and products offered by the Users on our app or the payment details of the Users. \r\n" +
        "26. EXPRESS RELEASE:\r\n" +
        "You expressly agree to release us [including our directors, agents, officers, employees, affiliates and subsidiaries] from claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with your disputes amongst users or third parties through or on our app. \r\n" +
        "27. LIMITATION OF JURISDICTION:\r\n" +
        "In some jurisdictions, certain exemptions or limitations, as described in this agreement do not hold. In such jurisdictions, the limitations and exemptions shall apply to the maximum permissible extent. \r\n" +
        "28. USER AGREEMENT AS DEFENSE:\r\n" +
        "The suits which are impliedly or specifically barred by this agreement shall be opposed by us by pleading this agreement. \r\n" +
        "29. CLASS ACTIONS ARE BARRED:\r\n" +
        "You expressly agree that you will not bring any class action against us unless we agree to such proceedings against us. Unless both parties agree, the arbitrator shall not consolidate or join the proceedings against us or you as a class of users. \r\n" +
        "30. NOTICES:\r\n" +
        "30.1 Any notices must be given by email to us;\r\n" +
        "Attn: Legal Department_________________________________________________________________________.\r\n" +
        "30.2 In your case, we will send you any notice at your provided email address (either during the registration process or when your email address changes). Notice shall be deemed given 24 hours after email is sent, unless the sending party is notified that the email address is invalid. Alternatively, we may give you notice by certified mail, postage prepaid and return receipt requested, to the address provided to us. In such case, notice shall be deemed given three days after the date of mailing.\r\n" +
        "31. OUR SERVICE AND GUARANTEES:\r\n" +
        "Our app reserves the right to modify or terminate the app’s service for any reason, without notice, at any time. We also reserve the right to sell, alter, transfer or delegate our rights under this agreement to anyone without any prior notice to you. Our app does not guarantee continuous, uninterrupted access to the app, and operation of the app may be interfered with by numerous factors outside our control.\r\n" +
        "32. FOREIGN JURISDICTION:\r\n" +
        "The services of our app are available globally. By agreeing to our policy, you warrant that it is completely legal to use our services and app in your country. It is the duty of the user to verify any potential violation. The user agrees to indemnify us or sister companies, employees, agents or any related individual or organization for any liability it might incur in a foreign jurisdiction.  Our services shall not be deemed to constitute an offer to sell or serve in countries where it is illegal to do so. We reserve the right to monitor the location from which you access the app and to block access from any jurisdiction in which participation is illegal or restricted.\r\n" +
        "33. LINKS TO OTHER WEBSITES:\r\n" +
        "Links to third party Websites on this site are provided solely as a convenience to you. If you use these links, a new browser will be lodged to access linked Websites. We have not reviewed these third party Websites and does not control and is not responsible for any of these Websites or their content. We do not endorse or make any representations about them, or any information, or other products or materials found there, or any results that may be obtained from using them. If you decide to access any of the third party Websites linked to this app, you do this entirely at your own risk.\r\n" +
        "34. NO WAIVER IMPLIED:\r\n" +
        "The failure of us to enforce at any time any of the provisions of these of Agreement, or the failure to require at any time performance by you of any of the provisions of these provisions, shall in no way be construed to be a present or future waiver of such provisions, nor in any way affect the our right to enforce each and every such provision thereafter. The express waiver by us of any provision, condition or requirement of these provisions shall not constitute a waiver of any future obligation to comply with such provision, condition or requirement.\r\n" +
        "35. SEVERABILITY:\r\n" +
        "Each Term shall be deemed to be severable. If any Term or portion thereof is found to be invalid or unenforceable, such invalidity or unenforceability shall in no way effect the validity or enforceability of any other Term.\r\n" +
        "36. ASSIGNMENT:\r\n" +
        "36.1 You will not assign any rights or delegate any obligations under these Terms, in whole or in part, by operation of law or otherwise, without obtaining our prior written consent, which may be withheld in our sole discretion. \r\n" +
        "36.2 We may assign our rights and delegate any of our obligations under these Terms, in whole or in part, without your consent. Any assignment or delegation in violation of the foregoing will be null and void. These Terms will be binding and inure to the benefit of each party’s permitted successors and assigns.\r\n" +
        "37. FORCE MAJEURE:\r\n" +
        "We shall be under no liability to you in respect of anything that, if not for this provision, would or might constitute a breach of these Terms, where this arises out of circumstances beyond our control, including but not limited to:\r\n" +
        "(a) acts of god;\r\n" +
        "(b) natural disasters;\r\n" +
        "(c) sabotage;\r\n" +
        "(d) accident;\r\n" +
        "(e) riot;\r\n" +
        "(f) shortage of supplies, equipment, and materials;\r\n" +
        "(g) strikes and lockouts;\r\n" +
        "(h) civil unrest;\r\n" +
        "(i) Computer hacking; or\r\n" +
        "(j) malicious damage.\r\n" +
        "38. DIGITAL SIGNATURE:\r\n" +
        "38.1 By using our services, you are deemed to have executed this Agreement electronically, effective on the date you register your Account and start using our services. Your Account registration constitutes an acknowledgement that you are able to electronically receive, download, and print this Agreement.\r\n" +
        "38.2 In connection with this Agreement, you may be entitled to receive certain records, such as contracts, notices, and communications, in writing. To facilitate your use of the app, you give us permission to provide these records to you electronically instead of in paper form.\r\n" +
        "38.3 By registering for an Account, you consent to electronically receive and access, via email, all records and notices for the services provided to you under this Agreement that we would otherwise be required to provide to you in paper form. However, we reserve the right, in our sole discretion, to communicate with you via the Postal Service and other third-party mail services using the address under which your account is registered. Your consent to receive records and notices electronically will remain in effect until you withdraw it. You may withdraw your consent to receive further records and notices electronically at any time by contacting Customer Support. If you withdraw your consent to receive such records and notices electronically, we will terminate your access to the Services, and you will no longer be able to use the Services. Any withdrawal of your consent to receive records and notices electronically will be effective only after we have a reasonable period of time to process your request for withdrawal. Please note that your withdrawal of consent to receive records and notices electronically will not apply to records and notices electronically provided by us to you before the withdrawal of your consent becomes effective.\r\n" +
        "38.4 In order to ensure that we are able to provide records and notices to you electronically, you must notify us of any change in your email address by updating your Account information on the app or by contacting Customer Support.\r\n" +
        "39. MODIFICATION:\r\n" +
        "The Terms and Conditions cannot be modified on an individual basis by any person affiliated, or claiming affiliation, with us. Nothing in this section will prevent us from modifying the terms of these Terms and Conditions and posting such modifications on our app. We reserve the right, in our sole and exclusive discretion, to revise these terms and conditions at any time. All revisions shall be posted on this page. Since you are bound by all revisions made by us, you should review this page each time you connect to our app. It is important that you fully read and understand the terms and conditions you are agreeing to be bound by, when you use this app.\r\n" +
        "40. DISCLAIMER OF WARRANTIES:\r\n" +
        "40.1 ALL CONTENT AND SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THIS APP ARE PROVIDED “WITH ALL FAULTS” AND ON AN “AS IS” AND “AS AVAILABLE” BASIS, UNLESS OTHERWISE SPECIFIED IN WRITING. WE MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, AS TO THE OPERATION OF THIS APP OR THE CONTENT OR SERVICES INCLUDED ON, OR OTHERWISE MADE AVAILABLE TO YOU THROUGH, THIS APP, UNLESS OTHERWISE SPECIFIED IN WRITING, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE, NON-INFRINGEMENT, QUIET ENJOYMENT, AND ACCURACY. YOU EXPRESSLY AGREE THAT YOUR USE OF THIS APP IS AT YOUR SOLE RISK.\r\n" +
        "40.2 We make no warranty that the App or Services will meet your requirements, or that the App and/or Services will be uninterrupted, timely, secure, or error free; nor do we make any warranty as to the results that may be obtained from the use of the App or Services, or that defects in the App or Services will be corrected. You understand and agree that you will be solely responsible for any damage to your device or loss of data that results from the download of any material and/or Content. No advice or information, whether oral or written, obtained by you from us through the App, Services or otherwise will create any warranty, representation or guarantee not expressly stated in these Terms of Use.\r\n" +
    "40.3 We do not investigate, represent or endorse the accuracy, legality, legitimacy, validity or reliability of any services, deals, coupons or other promotions or materials, including advice, ratings, and recommendations contained on, distributed through, or linked, downloaded or accessed from the website/App.\r\n" +
        "41. LIMITATION OF LIABILITY:\r\n" +
        "41.1 WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOOD-WILL, OR OTHER INTANGIBLE LOSSES. WE SHALL ALSO NOT BE LIABLE FOR ANY DAMAGES OR LOSSES RESULTING FROM (A) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE APP; (B) THE COST OF PROCUREMENT OF SUBSTITUTE SERVICES; (C) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY USING THE WEBSITE/APP, INCLUDING, BUT NOT LIMITED TO, ANY DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF MEMBERS AND OTHER USERS OR THIRD PARTIES; (D) ANY CONTENT OBTAINED FROM THE WEBSITE/APP; OR (E) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT.\r\n" +
        "41.2 IN NO EVENT SHALL OUR AGGREGATE LIABILITY EXCEED THE GREATER OF _______________________________ (amount). FOR THE AVOIDANCE OF DOUBT, THE FOREGOING LIMITS THE LIABILITY OF ALL WEBSITE/APP ENTITIES IN THE AGGREGATE TO THE AMOUNT STATED.\r\n" +
        "41.3 THE LIMITATIONS OF THIS SECTION SHALL APPLY TO ANY THEORY OF LIABILITY, WHETHER BASED ON WARRANTY, CONTRACT, STATUTE, TORT (INCLUDING NEGLIGENCE), OR OTHERWISE, AND WHETHER OR NOT ANY OF THE WEBSITE/APP ENTITIES HAS BEEN INFORMED OF THE POSSIBILITY OF ANY SUCH DAMAGE, AND EVEN IF A REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.\r\n" +
        "41.4 IF ANY OF THE ABOVE LIMITATIONS DOES NOT APPLY TO YOU BECAUSE YOU ARE ACCESSING WEBSITE/APP FROM A JURISDICTION THAT DOES NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, THESE LIMITATIONS WILL APPLY TO YOU TO THE MAXIMUM EXTENT ALLOWABLE UNDER APPLICABLE LAW.\r\n" +
        "42. COMMUNICATIONS:\r\n" +
        "42.1 Our app’s team may send you information about offers, notices, letters and other communication to your email. You can ask us to refrain from sending you offers or promotional offers at info@havr.ca.\r\n" +
        "42.2 You consent to receive notices and information from us in respect of the app and Services by electronic communication. You may withdraw this consent at any time, but if you do so we may choose to suspend or close your Account.\r\n" +
        "43. ENTIRE AGREEMENT:\r\n" +
        "The Agreement, in connection with the other obligations and rules detailed in writing on the app, constitute the entire agreement between you and the app and cannot be modified by you. The Terms and Conditions cannot be modified on an individual basis by any person affiliated, or claiming affiliation, with the app. Nothing in this subsection will prevent the app from modifying the terms of these Terms and Conditions and posting such\r\n" +
        "44. CONTACT US:\r\n" +
        "44.1 For any further clarification of our Terms and Conditions, please write to us at info@havr.ca.\r\n" +
        "44.2 Our Permanent Address is info@havr.ca. \r\n" +
        "44.3 Our legal representatives can be contacted at __________________________________. \r\n" +
    "44.4 Our Dispute Resolution team can be contacted at info@havr.ca. \r\n"

    
}
